import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/global.css";
import Link from "next/link";

const geistSans = localFont({
  src: "/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Crer Presentes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <header className="border-b-2 border-white">
          <div className="navbar flex flex-row justify-between bg-base-100">
            <div className="flex-1">
              <Link href={"#"} className="btn btn-ghost text-xl">
                Crer Presentes
              </Link>
            </div>
            <button className="btn btn-ghost btn-circle">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                />
              </svg>
            </button>
            <div className="form-control">
              <input
                type="text"
                placeholder="Search..."
                className="input input-bordered w-24 md:w-auto"
              />
            </div>
            <ul
              tabIndex={0}
              className="menu menu-vertical md:menu-horizontal rounded-box"
            >
              <li>
                <Link href={"#"}>Item 1</Link>
              </li>
              <li>
                <Link href={"#"}>Item 2</Link>
              </li>
              <li>
                <Link href={"#"}>Item 3</Link>
              </li>
            </ul>
            <div className="flex-none">
              <div className="dropdown dropdown-end">
                <div
                  tabIndex={0}
                  role="button"
                  className="btn btn-ghost btn-circle"
                >
                  <div className="indicator">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
                      />
                    </svg>
                    <span className="badge badge-sm indicator-item">0</span>
                  </div>
                </div>
                <div
                  tabIndex={0}
                  className="card card-compact dropdown-content bg-base-100 z-[1] mt-3 w-52 shadow"
                >
                  <div className="card-body">
                    <span className="text-lg font-bold">0 Items</span>
                    <span className="text-info">Subtotal: R$0</span>
                    <div className="card-actions">
                      <button className="btn btn-primary btn-block">
                        View cart
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>

        {children}

        <footer className="footer p-5 bg-base-100 mt-10 border-t-2 border-white">
          <address>
            <p>Tel. </p>
            <p>Email. </p>
            <p>Endereço. </p>
            <p>CNPJ. </p>
          </address>
        </footer>
      </body>
    </html>
  );
}
