import { createContext } from "@/trpc/server/context";
import { appRouter } from "@/trpc/server/router/appRouter";
import { fetchRequestHandler } from "@trpc/server/adapters/fetch";

export const runtime = "nodejs";

/**
 * Handles incoming HTTP requests and routes them to the appropriate tRPC endpoint.
 *
 * @param {Request} req - The incoming HTTP request object.
 * @return {Promise<Response>} A promise that resolves to the HTTP response generated by the request handler.
 */
export async function handler(req: Request) {
  return fetchRequestHandler({
    endpoint: "/api/trpc",
    req,
    router: appRouter,
    createContext: createContext
  });
}

export { handler as GET, handler as POST, handler as PUT, handler as DELETE };
